name: Clean workflow runs
on:
  # schedule:
  #   - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  cleanup:
    runs-on: ubuntu-latest
    steps:
      - name: Clean workflow runs
        uses: c-hive/gha-remove-workflows@v1
        with:
          keep_days: 1
          keep_min: 3
          delete_workflow_pattern: '.*'
