name: Deploy to PythonAnywhere

on:
  workflow_dispatch:

jobs:
  call-webhook:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger deploy
        run: |
          curl https://dmikes.eu.pythonanywhere.com/update?secret=${{ secrets.DEPLOY_SECRET }}
