name: Deploy to PythonAnywhere

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Trigger deploy webhook
      run: |
        curl -X GET \
        -H "Authorisation: Bearer ${{ secrets.DEPLOY_TOKEN }}" \
        "${{ secrets.DEPLOY_URL }}"
