name: Reload on PythonAnywhere

on:
  schedule:
    - cron: '0 0 1 * *'
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Trigger reload webhook
      run: |
        curl -X GET \
          -H "Authorisation: Bearer ${{ secrets.DEPLOY_TOKEN }}" \
          "${{ secrets.RELOAD_URL }}"
