name: Update PythonAnywhere

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
    - name: Trigger update webhook
      run: |
        curl -X GET \
        -H "Authorisation: Bearer ${{ secrets.ACCESS_TOKEN }}" \
        "${{ secrets.DEPLOY_URL }}"
